### Create a new song
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Song 3",
  "artist":   "Artist 1, Artist 2",
  "url": "https://open.spotify.com/track/59B6XA5N4lOXPP5a0TxRSZ"
}

### Get song by ID
GET http://localhost:3000/songs/738fbe73-e09b-4f9a-bce3-cfa8c46fb57e

### Get songs with sorting
GET http://localhost:3000/songs?sortBy=createdAt

### Get songs with total play sorting
GET http://localhost:3000/songs?sortBy=totalPlay

### Update a song
PUT http://localhost:3000/songs/738fbe73-e09b-4f9a-bce3-cfa8c46fb57e
Content-Type: application/json

{
  "title":  "Updated Song 1",
  "artist": "Updated Artist 1"
}

### Delete a song
DELETE http://localhost:3000/songs/738fbe73-e09b-4f9a-bce3-cfa8c46fb57e

### Play a song
GET http://localhost:3000/songs/738fbe73-e09b-4f9a-bce3-cfa8c46fb57e/play